collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1530612
  brandStrength: 0.5730397
  rhythmicContrast: 0.0596133
  brandColors:
    - '#D0D0D0'
    - '#808080'
    - '#FEFEFE'
    - '#181818'
    - '#606060'
  lightness: 0.2293233
typography_spectrum: 0.714482918381691
layout_spectrum: 0.5171858
name: maksbyart
