collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.714482918381691
color:
  saturation: 0.1530612
  brandStrength: 0.2142857
  lightness: 0.2293233
  brandColors:
    - '#FFFFFF'
    - '#909090'
    - '#C0C0C0'
    - '#606060'
    - '#3A3A3A'
  rhythmicContrast: 0.0596133
layout_spectrum: 0.9726101
name: maksbyart
